# Generated by Django 5.1.1 on 2024-09-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Characters",
            new_name="Character",
        ),
    ]
